if(EXISTS "D:/Code/C++/MultiFlappyBird/build-ninja/flappy_tests-b12d07c_tests.cmake")
  include("D:/Code/C++/MultiFlappyBird/build-ninja/flappy_tests-b12d07c_tests.cmake")
else()
  add_test(flappy_tests_NOT_BUILT-b12d07c flappy_tests_NOT_BUILT-b12d07c)
endif()
