add_test( [==[Bird hits top bound]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Bird hits top bound]==]  )
set_tests_properties( [==[Bird hits top bound]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[Bird hits bottom bound]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Bird hits bottom bound]==]  )
set_tests_properties( [==[Bird hits bottom bound]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[Bird does not collide inside the gap]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Bird does not collide inside the gap]==]  )
set_tests_properties( [==[Bird does not collide inside the gap]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[Bird collides with pipe when outside gap]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Bird collides with pipe when outside gap]==]  )
set_tests_properties( [==[Bird collides with pipe when outside gap]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[GameSession starts match only after countdown]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[GameSession starts match only after countdown]==]  )
set_tests_properties( [==[GameSession starts match only after countdown]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[GameSession tick updates snapshot when match is in progress]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[GameSession tick updates snapshot when match is in progress]==]  )
set_tests_properties( [==[GameSession tick updates snapshot when match is in progress]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[GameSession eventually finishes]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[GameSession eventually finishes]==]  )
set_tests_properties( [==[GameSession eventually finishes]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
set( flappy_tests_TESTS [==[Bird hits top bound]==] [==[Bird hits bottom bound]==] [==[Bird does not collide inside the gap]==] [==[Bird collides with pipe when outside gap]==] [==[GameSession starts match only after countdown]==] [==[GameSession tick updates snapshot when match is in progress]==] [==[GameSession eventually finishes]==])
