add_test( [==[Bird hits top bound]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Bird hits top bound]==]  )
set_tests_properties( [==[Bird hits top bound]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[Bird hits bottom bound]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Bird hits bottom bound]==]  )
set_tests_properties( [==[Bird hits bottom bound]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[Bird does not collide inside the gap]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Bird does not collide inside the gap]==]  )
set_tests_properties( [==[Bird does not collide inside the gap]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[Bird collides with pipe when outside gap]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Bird collides with pipe when outside gap]==]  )
set_tests_properties( [==[Bird collides with pipe when outside gap]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[GameSession starts match only after countdown]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[GameSession starts match only after countdown]==]  )
set_tests_properties( [==[GameSession starts match only after countdown]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[GameSession tick updates snapshot when match is in progress]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[GameSession tick updates snapshot when match is in progress]==]  )
set_tests_properties( [==[GameSession tick updates snapshot when match is in progress]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[GameSession eventually finishes]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[GameSession eventually finishes]==]  )
set_tests_properties( [==[GameSession eventually finishes]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[Tick does nothing before StartMatch]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Tick does nothing before StartMatch]==]  )
set_tests_properties( [==[Tick does nothing before StartMatch]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[Jump affects only the targeted player]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Jump affects only the targeted player]==]  )
set_tests_properties( [==[Jump affects only the targeted player]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[Distance increases while player is alive]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Distance increases while player is alive]==]  )
set_tests_properties( [==[Distance increases while player is alive]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[Player dies on collision]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[Player dies on collision]==]  )
set_tests_properties( [==[Player dies on collision]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[BuildResult sorts players by distance]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[BuildResult sorts players by distance]==]  )
set_tests_properties( [==[BuildResult sorts players by distance]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
add_test( [==[BuildSnapshot conatains x position]==] [==[C:/Code/C++/FlappyDappy/build-ninja/flappy_tests.exe]==] [==[BuildSnapshot conatains x position]==]  )
set_tests_properties( [==[BuildSnapshot conatains x position]==] PROPERTIES WORKING_DIRECTORY [==[C:/Code/C++/FlappyDappy/build-ninja]==])
set( flappy_tests_TESTS [==[Bird hits top bound]==] [==[Bird hits bottom bound]==] [==[Bird does not collide inside the gap]==] [==[Bird collides with pipe when outside gap]==] [==[GameSession starts match only after countdown]==] [==[GameSession tick updates snapshot when match is in progress]==] [==[GameSession eventually finishes]==] [==[Tick does nothing before StartMatch]==] [==[Jump affects only the targeted player]==] [==[Distance increases while player is alive]==] [==[Player dies on collision]==] [==[BuildResult sorts players by distance]==] [==[BuildSnapshot conatains x position]==])
